[2025-10-17T09:03:39.473+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-17T09:03:39.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag3.test_date manual__2025-10-17T09:03:35.093542+00:00 [queued]>
[2025-10-17T09:03:39.500+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag3.test_date manual__2025-10-17T09:03:35.093542+00:00 [queued]>
[2025-10-17T09:03:39.501+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-17T09:03:39.513+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): test_date> on 2025-10-17 09:03:35.093542+00:00
[2025-10-17T09:03:39.596+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=294) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-17T09:03:39.598+0000] {standard_task_runner.py:63} INFO - Started process 299 to run task
[2025-10-17T09:03:39.598+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag3', 'test_date', 'manual__2025-10-17T09:03:35.093542+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpmy2cd9nb']
[2025-10-17T09:03:39.600+0000] {standard_task_runner.py:91} INFO - Job 262: Subtask test_date
[2025-10-17T09:03:39.613+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-10-17T09:03:39.650+0000] {task_command.py:426} INFO - Running <TaskInstance: dag3.test_date manual__2025-10-17T09:03:35.093542+00:00 [running]> on host 5b9dfa83b040
[2025-10-17T09:03:39.721+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag3' AIRFLOW_CTX_TASK_ID='test_date' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T09:03:35.093542+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T09:03:35.093542+00:00'
[2025-10-17T09:03:39.723+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-17T09:03:39.724+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T09:03:39.725+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'date']
[2025-10-17T09:03:39.735+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T09:03:39.737+0000] {subprocess.py:93} INFO - Fri Oct 17 09:03:39 UTC 2025
[2025-10-17T09:03:39.738+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T09:03:39.738+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-17T09:03:39.759+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag3, task_id=test_date, run_id=manual__2025-10-17T09:03:35.093542+00:00, execution_date=20251017T090335, start_date=20251017T090339, end_date=20251017T090339
[2025-10-17T09:03:39.812+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-17T09:03:39.828+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-17T09:03:39.830+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
